// <auto-generated />
using System;
using Appointment_system_managment.Data.ASM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Appointment_system_managment.Migrations
{
    [DbContext(typeof(database))]
    partial class databaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Appointment_system_managment.Models.appointment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Appointment_date_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Clinic_registration_no")
                        .HasColumnType("int");

                    b.Property<int>("Doctor_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Obj_ClinicID")
                        .HasColumnType("int");

                    b.Property<int?>("Obj_Doctor_DetailsID")
                        .HasColumnType("int");

                    b.Property<int?>("Obj_Patient_detailID")
                        .HasColumnType("int");

                    b.Property<int>("Patient_registration_no")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Obj_ClinicID");

                    b.HasIndex("Obj_Doctor_DetailsID");

                    b.HasIndex("Obj_Patient_detailID");

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("Appointment_system_managment.Models.clinic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Clinic_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clinic_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clinic_phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("clinic");
                });

            modelBuilder.Entity("Appointment_system_managment.Models.doctor_detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sepicaligation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("doctor_detail");
                });

            modelBuilder.Entity("Appointment_system_managment.Models.patient_detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("patient_detail");
                });

            modelBuilder.Entity("Appointment_system_managment.Models.appointment", b =>
                {
                    b.HasOne("Appointment_system_managment.Models.clinic", "Obj_Clinic")
                        .WithMany()
                        .HasForeignKey("Obj_ClinicID");

                    b.HasOne("Appointment_system_managment.Models.doctor_detail", "Obj_Doctor_Details")
                        .WithMany()
                        .HasForeignKey("Obj_Doctor_DetailsID");

                    b.HasOne("Appointment_system_managment.Models.patient_detail", "Obj_Patient_detail")
                        .WithMany()
                        .HasForeignKey("Obj_Patient_detailID");

                    b.Navigation("Obj_Clinic");

                    b.Navigation("Obj_Doctor_Details");

                    b.Navigation("Obj_Patient_detail");
                });
#pragma warning restore 612, 618
        }
    }
}
